### ISSUE TITLE
NameError: name 'fundamental' is not defined

### ISSUE THREAD

**Issue by ghost** [steven2K19/Dataframe_fundamental#1]
Dear Mr. Wang
Firstly I wanna thank you for this excellent product, which can solve so difficult problem. 
But I have faced with  some difficulties. I had copied the example, corrected and got the next:
 
[Traceback (most recent call last):
File "C:\Users\путин\AppData\Local\Programs\Python\Python37\Питон АНАЛИЗ\MSFT GOOG FB.py", line 6, in <module>
df = fundamental.get_df_list(symlist)
NameError: name 'fundamental' is not defined].

If i do so:
from fundamental import fundamental
symlist=['GOOG','MSFT','FB']
df = fundamental.get_df_list(symlist)

I get the next
Traceback (most recent call last):
  File "C:\Users\путин\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Basic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\путин\AppData\Local\Programs\Python\Python37\Питон АНАЛИЗ\MSFT GOOG FB.py", line 5, in <module>
    df = fundamental.get_df_list(symlist)
  File "C:\Users\путин\AppData\Local\Programs\Python\Python37\lib\site-packages\fundamental\fundamental.py", line 223, in get_df_list
    masterdf = get_df('MSFT')
  File "C:\Users\путин\AppData\Local\Programs\Python\Python37\lib\site-packages\fundamental\fundamental.py", line 80, in get_df
    sharelist = list(dfe['Basic'].dropna())
  File "C:\Users\путин\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\путин\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Basic'

Please show full example of using this useful thing.

BEST WISHES&REGARDS

Your wfve3256

**Comment by steven2K19** [comment]
Sorry for the late replay.
I have both Apple and Windows computers.
It does not work on Apple computers.
Sorry for the inconvenience.




Steven Wang


________________________________
